#!/bin/sh

# this should be temporary until we have proper module packaging
cd /home/jrh/souspi/

# make sure controller is running first
sv start souspi-controller || exit 1

exec chpst -u souspi:souspi /usr/bin/python ./SousVideWebUI.py
